import * as THREE from 'three';
import { Scene } from './Scene';
import { History as UndoHistory } from './History';
import { AddObjectCommand } from './Commands';
import {
  makeCube,
  makeSphere,
  makeCylinder,
  makePlane,
  makeTorus,
  makePointLight,
} from './Primitives';
import {
  addScriptDescriptor,
  registerScript,
  ScriptCtx,
  Script as ScriptInstance,
} from './Script';

// Renderer-side dispatchers for the engine-scoped tools Claude can call.
// Each tool returns a JSON-encoded result string that goes back to the model
// as a tool_result block.

const PRIMITIVE_FACTORIES: Record<string, () => THREE.Object3D> = {
  cube: makeCube,
  sphere: makeSphere,
  cylinder: makeCylinder,
  plane: makePlane,
  torus: makeTorus,
  point_light: makePointLight,
};

export function dispatchEngineTool(
  name: string,
  input: Record<string, unknown>,
  scene: Scene,
  history: UndoHistory,
): string {
  try {
    if (name === 'engine_add_primitive') {
      return engineAddPrimitive(input, scene, history);
    }
    if (name === 'engine_list_scene') {
      return engineListScene(scene);
    }
    if (name === 'engine_attach_script') {
      return engineAttachScript(input, scene);
    }
    if (name === 'engine_create_behavior') {
      return engineCreateBehavior(input, scene);
    }
    return JSON.stringify({ error: `unknown tool: ${name}` });
  } catch (err) {
    return JSON.stringify({ error: (err as Error).message });
  }
}

function engineAddPrimitive(
  input: Record<string, unknown>,
  scene: Scene,
  history: UndoHistory,
): string {
  const type = String(input.type ?? '');
  const factory = PRIMITIVE_FACTORIES[type];
  if (!factory) {
    return JSON.stringify({ error: `unknown primitive: ${type}` });
  }
  const obj = factory();
  if (input.name && typeof input.name === 'string') {
    obj.name = input.name;
  }
  if (Array.isArray(input.position) && input.position.length === 3) {
    const [x, y, z] = input.position as number[];
    obj.position.set(Number(x) || 0, Number(y) || 0, Number(z) || 0);
  }
  if (input.color && typeof input.color === 'string') {
    const mesh = obj as THREE.Mesh;
    const mat = mesh.material as THREE.MeshStandardMaterial | undefined;
    if (mat && mat.color) {
      try {
        mat.color.set(input.color);
      } catch {
        // ignore bad color
      }
    }
  }
  history.push(new AddObjectCommand(scene, obj));
  return JSON.stringify({
    added: {
      name: obj.name,
      type: obj.type,
      position: [obj.position.x, obj.position.y, obj.position.z],
    },
  });
}

function engineAttachScript(
  input: Record<string, unknown>,
  scene: Scene,
): string {
  const objectName = String(input.objectName ?? '');
  const scriptType = String(input.scriptType ?? '');
  const params = (input.params as Record<string, unknown> | undefined) ?? {};
  const obj = findInEditable(scene, objectName);
  if (!obj) return JSON.stringify({ error: `no object named "${objectName}"` });
  addScriptDescriptor(obj, { type: scriptType, params });
  scene.notifyChanged();
  return JSON.stringify({ attached: scriptType, to: obj.name });
}

// Track custom behaviors registered at runtime so engine_create_behavior can
// keep slot names unique and so we can avoid double-registering on rebuild.
let nextBehaviorId = 1;

function engineCreateBehavior(
  input: Record<string, unknown>,
  scene: Scene,
): string {
  const objectName = String(input.objectName ?? '');
  const behaviorName = String(input.behaviorName ?? 'CustomBehavior')
    .replace(/[^A-Za-z0-9_]/g, '')
    .slice(0, 32) || 'CustomBehavior';
  const body = String(input.body ?? '');
  if (!body) return JSON.stringify({ error: 'empty body' });

  const obj = findInEditable(scene, objectName);
  if (!obj) return JSON.stringify({ error: `no object named "${objectName}"` });

  // Wrap the user-supplied body in a Function. The closure receives dt and
  // pulls owner/scene/input/camera/THREE from the script context.
  let bodyFn: (
    dt: number,
    owner: THREE.Object3D,
    scene: THREE.Scene,
    input: ScriptCtx['input'],
    camera: THREE.PerspectiveCamera,
    three: typeof THREE,
  ) => void;
  try {
    bodyFn = new Function(
      'dt',
      'owner',
      'scene',
      'input',
      'camera',
      'THREE',
      body,
    ) as typeof bodyFn;
  } catch (err) {
    return JSON.stringify({
      error: `Failed to compile behavior: ${(err as Error).message}`,
    });
  }

  // Register a fresh Script type per behavior. The type name is namespaced
  // so multiple custom behaviors on different objects don't collide.
  const type = `Behavior_${behaviorName}_${nextBehaviorId++}`;
  registerScript({
    type,
    label: behaviorName,
    description: 'Custom behavior generated by Claude.',
    params: [],
    create: (ctx: ScriptCtx): ScriptInstance => ({
      update(dt: number) {
        try {
          bodyFn(dt, ctx.owner, ctx.scene.three, ctx.input, ctx.camera, THREE);
        } catch (err) {
          console.error(`[${type}] runtime error:`, err);
        }
      },
    }),
  });

  addScriptDescriptor(obj, { type, params: {} });
  scene.notifyChanged();
  return JSON.stringify({
    attached: type,
    to: obj.name,
    note: 'Press Play to run.',
  });
}

function findInEditable(scene: Scene, name: string): THREE.Object3D | null {
  let result: THREE.Object3D | null = null;
  scene.editable.traverse((o) => {
    if (!result && o.name === name) result = o;
  });
  return result;
}

function engineListScene(scene: Scene): string {
  const roots = scene.editableRoots().map((obj) => ({
    name: obj.name || obj.type,
    type: obj.type,
    position: [
      Number(obj.position.x.toFixed(3)),
      Number(obj.position.y.toFixed(3)),
      Number(obj.position.z.toFixed(3)),
    ],
    rotation: [
      Number(obj.rotation.x.toFixed(3)),
      Number(obj.rotation.y.toFixed(3)),
      Number(obj.rotation.z.toFixed(3)),
    ],
    scale: [
      Number(obj.scale.x.toFixed(3)),
      Number(obj.scale.y.toFixed(3)),
      Number(obj.scale.z.toFixed(3)),
    ],
  }));
  return JSON.stringify({ object_count: roots.length, objects: roots });
}
